### ISSUE TITLE
Exception when using node 10.24.0

### ISSUE THREAD

**Issue by DarkTyger** [jslint-org/jslint#451]
**Replicate**

``` bash
$ sudo apt install -y npm
$ node --version
10.24.0
$ curl -L https://www.jslint.com/jslint.mjs > jslint.mjs
$ printf "console.log('hello world');\n" > hello.js
$ node jslint.mjs hello.js
```

**Expected**

Linter runs.

**Actual**

Linter does not run.

``` 
export default Object.freeze(jslint_export);    // Export jslint as esm.
^^^^^^
SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

Is this too old a version of node?

**Comment by DarkTyger** [comment]
Upgrade node and npm:

```
sudo su -c 'curl -sL https://deb.nodesource.com/setup_18.x | bash -'
sudo apt-get install nodejs -y
sudo apt update
sudo apt upgrade
sudo npm install -g npm@10.4.0
node --version
npm --version
```
